import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { Activity, AlertTriangle, Bot, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardCheck, Database, FileSearch, Gauge, LayoutDashboard, LoaderCircle, Radar, RefreshCw, Search, Settings, ShieldAlert, ShieldCheck, Sparkles, Wifi, Zap } from 'lucide-react'
import { Alert, api, AuditEvent, Investigation, Level, RiskSummary, Stats, Transaction } from './lib/api'
import './styles.css'

const cash = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 })
const levels: Level[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']
type View = 'Overview' | 'Transactions' | 'Fraud Alerts' | 'AI Investigation' | 'Risk Analytics' | 'Approval Queue' | 'Audit Trail' | 'Settings'
const nav: { name: View; icon: React.ReactNode }[] = [
  { name: 'Overview', icon: <LayoutDashboard /> }, { name: 'Transactions', icon: <Database /> }, { name: 'Fraud Alerts', icon: <ShieldAlert /> }, { name: 'AI Investigation', icon: <Bot /> }, { name: 'Risk Analytics', icon: <Gauge /> }, { name: 'Approval Queue', icon: <ClipboardCheck /> }, { name: 'Audit Trail', icon: <FileSearch /> }, { name: 'Settings', icon: <Settings /> },
]
const tier = (score: number): Level => score >= 85 ? 'CRITICAL' : score >= 70 ? 'HIGH' : score >= 45 ? 'MEDIUM' : 'LOW'
const cls = (risk: Level) => risk.toLowerCase()
const stamp = (value: string) => new Date(value).toLocaleString([], { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })

function App() {
  const [view, setView] = useState<View>('Overview')
  const [stats, setStats] = useState<Stats | null>(null); const [summary, setSummary] = useState<RiskSummary | null>(null); const [alerts, setAlerts] = useState<Alert[]>([]); const [txs, setTxs] = useState<Transaction[]>([])
  const [selected, setSelected] = useState<Transaction | null>(null); const [audit, setAudit] = useState<AuditEvent[]>([]); const [ai, setAi] = useState<Investigation | null>(null)
  const [filter, setFilter] = useState<'ALL' | Level>('ALL'); const [sort, setSort] = useState('risk'); const [search, setSearch] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = async (keep?: string) => { setLoading(true); try { const [s, r, a, t] = await Promise.all([api.dashboard(), api.riskSummary(), api.alerts(), api.transactions()]); setStats(s); setSummary(r); setAlerts(a); setTxs(t); setSelected(t.find(x => x.id === (keep || selected?.id)) || [...t].sort((a, b) => b.risk_score - a.risk_score)[0]); setError('') } catch { setError('FinGuard API is unavailable. Retry after the backend is running.') } finally { setLoading(false) } }
  useEffect(() => { load() }, [])
  useEffect(() => { if (selected) { setAi(null); api.audit(selected.id).then(setAudit).catch(() => setAudit([])) } }, [selected?.id])
  const visible = useMemo(() => alerts.filter(a => (filter === 'ALL' || a.risk_level === filter) && `${a.transaction_id}${a.customer_id}${a.merchant}`.toLowerCase().includes(search.toLowerCase())).sort((a, b) => sort === 'amount' ? b.amount - a.amount : sort === 'newest' ? +new Date(b.timestamp) - +new Date(a.timestamp) : b.risk_score - a.risk_score), [alerts, filter, search, sort])
  if (loading && !stats) return <Loading />
  if (!stats || !summary || !selected) return <main className="fatal"><ShieldAlert /><h1>Connection unavailable</h1><button onClick={() => load()}><RefreshCw />Retry</button></main>
  const select = (id: string) => { const tx = txs.find(x => x.id === id); if (tx) { setSelected(tx); setView('AI Investigation') } }
  const investigate = async () => { setBusy(true); try { setAi(await api.investigate(selected.id)); setAudit(await api.audit(selected.id)) } catch { setError('Investigation failed; human review remains available.') } finally { setBusy(false) } }
  const simulate = async () => { setBusy(true); try { const result = await api.simulate(); await load(result.transaction.id); setView('AI Investigation') } catch { setError('Simulation failed.') } finally { setBusy(false) } }
  const decide = async (decision: 'approved' | 'escalated') => { setBusy(true); try { await api.decide(selected.id, decision); await load(selected.id); setAudit(await api.audit(selected.id)) } finally { setBusy(false) } }
  return <div className="shell"><aside className="sidebar"><div className="brand"><i><ShieldCheck /></i><b>FinGuard <em>AI</em><small>Financial Fraud Intelligence</small></b></div><div className="online"><span />ONLINE <b>SIMULATION MODE</b></div><nav>{nav.map(item => <button aria-current={view === item.name ? 'page' : undefined} className={view === item.name ? 'active' : ''} onClick={() => setView(item.name)} key={item.name}>{item.icon}{item.name}{item.name === 'Approval Queue' && <mark>{summary.human_reviews_required}</mark>}</button>)}</nav><footer>PROTOTYPE — Demonstration using synthetic financial transaction data. Not connected to real banking systems.</footer></aside><main><Header busy={busy} simulate={simulate} />{error && <div className="error">{error}<button onClick={() => setError('')}>Dismiss</button></div>}<ViewContent view={view} stats={stats} summary={summary} alerts={visible} allTransactions={txs} audit={audit} selected={selected} ai={ai} busy={busy} filter={filter} sort={sort} search={search} setFilter={setFilter} setSort={setSort} setSearch={setSearch} select={select} investigate={investigate} decide={decide} /></main></div>
}

function Header({ busy, simulate }: { busy: boolean; simulate: () => void }) { return <header><div><p>AI-POWERED RISK OPERATIONS</p><h1>Financial fraud intelligence <em>that explains itself.</em></h1><span>Detect anomalies, investigate evidence, and keep people in control.</span></div><div><label><Wifi />API CONNECTED</label><button className="simulate" disabled={busy} onClick={simulate}>{busy ? <LoaderCircle className="spin" /> : <Zap />}Simulate Transaction</button></div></header> }
function ViewContent(props: any) { const { view, stats, summary, alerts, allTransactions, audit, selected, ai, busy, filter, sort, search, setFilter, setSort, setSearch, select, investigate, decide } = props; if (view === 'Overview') return <><Kpis stats={stats} summary={summary} /><Analytics stats={stats} summary={summary} /><section className="work"><AlertCenter alerts={alerts} filter={filter} sort={sort} search={search} setFilter={setFilter} setSort={setSort} setSearch={setSearch} select={select} selected={selected.id} /><Detail tx={selected} ai={ai} busy={busy} audit={audit} investigate={investigate} decide={decide} /></section></>; if (view === 'Transactions') return <Transactions txs={allTransactions} select={select} />; if (view === 'Fraud Alerts') return <AlertCenter alerts={alerts} filter={filter} sort={sort} search={search} setFilter={setFilter} setSort={setSort} setSearch={setSearch} select={select} selected={selected.id} />; if (view === 'AI Investigation') return <Detail tx={selected} ai={ai} busy={busy} audit={audit} investigate={investigate} decide={decide} />; if (view === 'Risk Analytics') return <Analytics stats={stats} summary={summary} expanded />; if (view === 'Approval Queue') return <ApprovalQueue txs={allTransactions} select={select} />; if (view === 'Audit Trail') return <AuditTrail events={audit} />; if (view === 'Settings') return <SettingsView />; return null }
function Kpis({ stats, summary }: { stats: Stats; summary: RiskSummary }) { const data = [['Transactions analyzed', stats.total_transactions, Database, 'Synthetic transactions evaluated'], ['Anomalies detected', stats.flagged_transactions, Activity, `${summary.anomaly_rate}% of dataset`], ['Critical alerts', summary.distribution.CRITICAL, ShieldAlert, 'Hold & verify required'], ['High risk cases', summary.distribution.HIGH, AlertTriangle, 'Manual review required'], ['Human reviews', summary.human_reviews_required, ClipboardCheck, 'Awaiting analyst action'], ['Transaction value', cash.format(stats.amount_monitored), CircleDollarSign, 'Synthetic volume']]; return <section className="kpis">{data.map(([n, v, I, d]) => { const Icon = I as typeof Database; return <article key={String(n)}><i><Icon /></i><span>{String(n)}<b>{String(v)}</b><small>{String(d)}</small></span></article> })}</section> }
function Analytics({ stats, summary, expanded }: { stats: Stats; summary: RiskSummary; expanded?: boolean }) { return <section className={`charts ${expanded ? 'analytics-full' : ''}`}><article><Title k="LIVE ML CLASSIFICATION" t="Risk distribution" /><div className="bars">{levels.map(l => <div key={l}><span className={cls(l)} /><b>{l}</b><i><em className={cls(l)} style={{ width: `${summary.distribution[l] / stats.total_transactions * 100}%` }} /></i><strong>{summary.distribution[l]}</strong></div>)}</div></article><article><Title k="ACTUAL SYNTHETIC VOLUME" t="Transaction value by risk" /><div className="columns">{[...levels].reverse().map(l => <div key={l}><span>{cash.format(summary.transaction_value_by_risk[l])}</span><i className={cls(l)} style={{ height: `${Math.max(8, summary.transaction_value_by_risk[l] / Math.max(...Object.values(summary.transaction_value_by_risk)) * 100)}%` }} /><b>{l}</b></div>)}</div></article><article><Title k="ISOLATION FOREST" t="Anomaly rate" /><div className="rate"><b>{summary.anomaly_rate}%</b><span>current transaction population</span></div><small>Live calculation from real API data; no simulated trend claims.</small></article></section> }
function AlertCenter({ alerts, filter, sort, search, setFilter, setSort, setSearch, select, selected }: any) { return <article className="alerts"><div className="heading"><div><p>FRAUD ALERT CENTER</p><h2>Prioritized risk signals</h2></div><select value={sort} onChange={e => setSort(e.target.value)}><option value="risk">Highest risk</option><option value="amount">Highest amount</option><option value="newest">Newest</option></select></div><div className="filters">{(['ALL', ...levels] as const).map(x => <button onClick={() => setFilter(x)} className={filter === x ? 'on' : ''} key={x}>{x}</button>)}<label><Search /><input placeholder="Search transactions" value={search} onChange={e => setSearch(e.target.value)} /></label></div><div className="rows">{alerts.length ? alerts.map((a: Alert) => <button onClick={() => select(a.transaction_id)} className={selected === a.transaction_id ? 'chosen' : ''} key={a.transaction_id}><mark className={cls(a.risk_level)}>{a.risk_level}</mark><span><b>{a.merchant}</b><small>{a.transaction_id} · {a.customer_id} · {a.location}</small><em>{a.risk_reasons.slice(0, 2).join(' · ')}</em></span><strong>{cash.format(a.amount)}</strong><i className={cls(a.risk_level)}>{a.risk_score}</i><ChevronRight /></button>) : <div className="empty">No alerts match this filter.</div>}</div></article> }
function Transactions({ txs, select }: { txs: Transaction[]; select: (id: string) => void }) { return <section className="page-panel"><Title k="TRANSACTIONS" t="Synthetic transaction population" /><div className="transaction-table">{txs.slice(0, 25).map(tx => <button onClick={() => select(tx.id)} key={tx.id}><span><b>{tx.id}</b><small>{tx.customer_id} · {tx.merchant} · {tx.country}</small></span><strong>{cash.format(tx.amount)}</strong><mark className={cls(tier(tx.risk_score))}>{tier(tx.risk_score)} · {tx.risk_score}</mark><ChevronRight /></button>)}</div></section> }
function ApprovalQueue({ txs, select }: { txs: Transaction[]; select: (id: string) => void }) { const items = txs.filter(tx => tx.review_status === 'pending_review' && tx.risk_score >= 70).sort((a, b) => b.risk_score - a.risk_score); return <section className="page-panel"><Title k="HUMAN-IN-THE-LOOP" t="Approval queue" /><p className="page-copy">CRITICAL cases require HOLD & VERIFY. HIGH cases require manual analyst review.</p><Transactions txs={items} select={select} /></section> }
function AuditTrail({ events }: { events: AuditEvent[] }) { return <section className="page-panel"><Title k="AUDIT TRAIL" t="Selected transaction event history" /><div className="trail large">{events.length ? events.slice().reverse().map(x => <div key={x.id}><i /><span><b>{x.event}</b><small>{stamp(x.timestamp)} · {x.detail}</small></span></div>) : <div className="empty">Select a transaction to view recorded events.</div>}</div></section> }
function SettingsView() { return <section className="page-panel"><Title k="SETTINGS" t="Demo environment" /><p className="page-copy">Simulation Mode is active. FinGuard uses synthetic data only, and OpenRouter credentials remain server-side.</p><div className="settings-list"><span><ShieldCheck /> API credentials are never exposed to React.</span><span><Database /> No real banking systems are connected.</span><span><Bot /> Qwen has a deterministic local fallback.</span></div></section> }
function Title({ k, t }: { k: string; t: string }) { return <div className="title"><p>{k}</p><h2>{t}</h2></div> }
function Detail({ tx, ai, busy, audit, investigate, decide }: { tx: Transaction; ai: Investigation | null; busy: boolean; audit: AuditEvent[]; investigate: () => void; decide: (d: 'approved' | 'escalated') => void }) { const l = tier(tx.risk_score), ratio = (tx.amount / tx.historical_average).toFixed(1); return <aside className="detail"><div className="detailtop"><div><p>AI FRAUD COMMAND CENTER</p><h2>{tx.id}</h2><small>{tx.customer_id} · {stamp(tx.timestamp)}</small></div><mark className={cls(l)}>{l} · {tx.risk_score}</mark></div><section><h3>Transaction overview</h3><div className="facts">{[['Amount', cash.format(tx.amount)], ['Merchant', tx.merchant], ['Location', tx.country], ['Device', tx.device], ['Payment', tx.payment_method], ['Baseline', `${cash.format(tx.historical_average)} · ${ratio}×`]].map(x => <span key={x[0]}>{x[0]}<b>{x[1]}</b></span>)}</div></section><section className="intelligence"><div className="meter"><i className={cls(l)} style={{ width: `${tx.risk_score}%` }} /></div><b>Risk intelligence · {l} · ML anomaly {tx.anomaly_score.toFixed(3)}</b><h3>Why this score?</h3>{tx.risk_factors.map(x => <p key={x}><Sparkles />{x}</p>)}</section><button className="qwen" onClick={investigate} disabled={busy}>{busy ? <LoaderCircle className="spin" /> : <Bot />}{busy ? 'Qwen AI is investigating…' : 'Investigate with Qwen AI'}</button>{ai ? <section className="answer"><div><Bot /><span><b>{ai.ai_provider === 'local_fallback' ? 'Local Demo Analysis' : 'Qwen AI Analysis'}</b><small>{ai.ai_provider}</small></span><strong>{ai.confidence}%</strong></div><h3>Executive risk summary</h3><p>{ai.summary}</p><h3>Key evidence</h3><aside>{ai.suspicious_factors.map(x => <i key={x}>{x}</i>)}</aside><h3>Possible fraud scenario</h3><p>{ai.possible_fraud_scenario}</p><footer><span>RECOMMENDED ACTION<b>{ai.recommended_action}</b></span><span>REVIEW<b>{ai.human_review_required ? 'HUMAN REVIEW REQUIRED' : 'AUTOMATED MONITORING'}</b></span></footer></section> : <section className="ready"><Radar /><b>Ready for investigation</b><span>Qwen AI will assess this transaction’s actual ML and behavioral signals.</span></section>}<section className="approval"><h3>Approval status</h3><mark className={tx.review_status}>{tx.review_status.replace('_', ' ')}</mark>{tx.review_status === 'pending_review' ? <div><button onClick={() => decide('escalated')}>Hold & verify</button><button onClick={() => decide('approved')}>Approve</button></div> : <p><CheckCircle2 />Decision recorded</p>}</section><section className="trail"><h3>Audit trail</h3>{audit.slice(0, 6).reverse().map(x => <div key={x.id}><i /><span><b>{x.event}</b><small>{stamp(x.timestamp)} · {x.detail}</small></span></div>)}</section></aside> }
function Loading() { return <main className="loading"><ShieldCheck /><h1>Loading FinGuard AI</h1></main> }
createRoot(document.getElementById('root')!).render(<App />)
